project_id = "kvlyupiwtuztyzjmltzf"

[functions.create-registration]
verify_jwt = false

[functions.transfer-registration]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-ecommerce-checkout]
verify_jwt = false
