// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvlyupiwtuztyzjmltzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bHl1cGl3dHV6dHl6am1sdHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0NDQ2MjMsImV4cCI6MjA5MjAyMDYyM30.TBZGrucnnzbOKZcNYOxUsj09VdbpSsolvOqX_qvWxpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});