// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyfijjwjalqwessnrxgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZmlqandqYWxxd2Vzc25yeGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NDYwMzUsImV4cCI6MjA4ODIyMjAzNX0.jhYYIsQanHB3yenL_jydE1h9slbEAmHBY24moWaG6J8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});